### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by SimonTestNet** [SimonTestNet/SimonTest#1]
I'm going to use this issue as a repo for images.

**Comment by SimonTestNet** [comment]
![image](https://cloud.githubusercontent.com/assets/25192526/22051607/bcb09dc4-dd01-11e6-84a0-33cbc78d7f5e.png)

**Comment by SimonTestNet** [comment]
![image](https://cloud.githubusercontent.com/assets/25192526/22051929/e982645c-dd03-11e6-83fb-2f3dcaf491bf.png)

**Comment by SimonTestNet** [comment]
![image](https://cloud.githubusercontent.com/assets/25192526/22052099/55264fd8-dd05-11e6-839c-3c544f0d71f7.png)

**Comment by SimonTestNet** [comment]
![image](https://cloud.githubusercontent.com/assets/25192526/22089899/739e982a-ddab-11e6-9277-5e67998bcdb3.png)

**Comment by SimonTestNet** [comment]
![image](https://cloud.githubusercontent.com/assets/25192526/22089910/8e55a578-ddab-11e6-866c-00edba71ef9b.png)

**Comment by SimonTestNet** [comment]
![image](https://cloud.githubusercontent.com/assets/25192526/22090088/bfb283a6-ddac-11e6-98b8-9c3782c5aa4d.png)

**Comment by SimonTestNet** [comment]
![image](https://cloud.githubusercontent.com/assets/25192526/22621547/6c34d500-eae3-11e6-8525-3cb0e4f40084.png)

**Comment by SimonTestNet** [comment]
![image](https://cloud.githubusercontent.com/assets/25192526/22913120/3a4f16b4-f226-11e6-99e1-02f8bb0c0b0c.png)

**Comment by ManuelDeLeon** [comment]
![image](https://user-images.githubusercontent.com/4257750/27661511-c105f294-5c17-11e7-9fff-0bf3f1c12f65.png)

![image](https://user-images.githubusercontent.com/4257750/27661517-c6d7439e-5c17-11e7-834c-e5a098801561.png)

![image](https://user-images.githubusercontent.com/4257750/27661530-d1da31ca-5c17-11e7-83ca-92ec26a16364.png)
