### ISSUE TITLE
Feature Request: Generate tests for other types besides Components

### ISSUE THREAD

**Issue by leocaseiro** [SimonTestNet/SimonTest#11]
Hi, @SimonTestNet.

This extension is awesome!

I was wondering how nice would be to generate scaffolding for other classes such as Pipes, Services, and so on...

What are your thoughts about it?

**Comment by ManuelDeLeon** [comment]
Started small... v0.15.0 scaffolds Pipes

**Comment by mackelito** [comment]
Would love to see this for services ;)

**Comment by ManuelDeLeon** [comment]
Continuing with the baby steps, it now scaffolds services. Just the skeleton for now, it will generate tests for properties and methods later.
