### ISSUE TITLE
forEach Error

### ISSUE THREAD

**Issue by lebsral** [SimonTestNet/SimonTest#12]
On one component I get this error.

`Cannot read property 'forEach' of undefined`

SimonTest is version 0.11.3
VScode is 1.12.1

**Comment by ManuelDeLeon** [comment]
Please post the component (removing everything not necessary to reproduce
the problem).

**Comment by SampadaBhagat** [comment]
I am getting the same error on one of my components.

**Comment by ManuelDeLeon** [comment]
I need a component to test with.
