### ISSUE TITLE
Feature Request: Provide Options that Generated Mock's Name's Prefix or  Suffix 

### ISSUE THREAD

**Issue by tomonari-t** [SimonTestNet/SimonTest#13]
Hi, @SimonTestNet.
This extension is so awesome!! It helps me a lot :)

# Feature

Provide option that Generated Mock's Name's Prefix or  Suffix 

# Why

I have started to use Simontest when I made some mocks have prefix "Mock".
So I modified some mock's name.

# Example

- MockFooService
- FooServiceStub
- ...

What are your thoughts about it?

Thanks!!

**Comment by ManuelDeLeon** [comment]
`// TODO: Insert lame excuse for replying so late`

It's not hard but I'm generally against adding configuration unless it adds a tangible benefit (personal preference is a weak argument). I'll close this for now but I'll be happy to revisit this if you can give me a good reason to implement it.

To give you an idea of my process for changing things, someone recommended grabbing stubs with the injectors (#7). My answer was basically the same I just gave you. A few weeks later someone else mentioned a problem of using stubs without using the injectors (#10). At that point I had to agree to change it.

btw, I'm very happy this extension helps you :)
