### ISSUE TITLE
Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by mackelito** [SimonTestNet/SimonTest#14]
Just installed it and get "Cannot read property 'forEach' of undefined" when right clicking on a component.ts file and selecting generate.

This does not happen on ALL components but on most.

**Comment by ManuelDeLeon** [comment]
Please post one of the components where it happens. Remove anything not necessary to reproduce the problem.

**Comment by mackelito** [comment]
Here you go!
[category-list.zip](https://github.com/SimonTestNet/SimonTest/files/1088263/category-list.zip)

**Comment by ManuelDeLeon** [comment]
Thanks for reporting it. Pick up `v0.13.1`
