### ISSUE TITLE
Static properties generate tests on the instance

### ISSUE THREAD

**Issue by MikePerilli** [SimonTestNet/SimonTest#17]
If you have a component with a property:
`public static Foo = false;`

SimonTest will generate a test on the instance like so:
`expect(comp.InitialNavigationComplete).toEqual(false);`

This should be `(<Class Name>.<propertyName>).toEqual(false);`
since the property is static.

**Comment by ManuelDeLeon** [comment]
Fixed on 0.17.3 =)
