### ISSUE TITLE
Cannot read property 'elements' of undefined in VS Code when generating tests

### ISSUE THREAD

**Issue by jakehockey10** [SimonTestNet/SimonTest#18]
I'm having trouble generating tests.  All I'm doing is right clicking the component I want to generate tests for:
![image](https://user-images.githubusercontent.com/1821383/29473959-fe1988ae-8416-11e7-8d42-a39aa0e93194.png)

and this is the error message I get:

![image](https://user-images.githubusercontent.com/1821383/29473978-0aec2e38-8417-11e7-8471-b9f1261fad66.png)

**Comment by ManuelDeLeon** [comment]
Please copy/paste the contents of app.component.ts

**Comment by ManuelDeLeon** [comment]
I can't do anything without a file/code to repro the issue...

**Comment by kbarendrecht** [comment]
@ManuelDeLeon I have the same error, and could provide code through PM/DM as I do not want to publicly publish it.

**Comment by ManuelDeLeon** [comment]
@kbarendrecht The less you give me the better. Please remove methods from your component until there's nothing else to remove and you can still reproduce the error. If you're still uncomfortable sharing that code then send it to my github username @ gmail.com

**Comment by kbarendrecht** [comment]
I've cut everything out, this seems like the most minimal sample. It seems to be a combination of things, as removing the Router import & constructor parameter fixes it, as well as removing the ./go-extension imports.

```
import { Component, OnInit, AfterViewInit, ViewChild, Input, } from '@angular/core';
import { trigger, state, style, transition, animate } from '@angular/animations';
import { Router } from '@angular/router';

import * as go from 'gojs';
import DragCreatingTool from './go-extensions/drag-creating-tool';
import RealtimeDragSelectingTool from './go-extensions/realtime-drag-selecting-tool';

@Component({
    selector: 'diagram-editor',
    templateUrl: './diagram-editor.component.html',
    styleUrls: ['./diagram-editor.component.css'],
})
export class DiagramEditorComponent implements OnInit, AfterViewInit {

    constructor(
        private router: Router
    ) { }

    ngOnInit() {

    }

    ngAfterViewInit() {

    }
}

```
