### ISSUE TITLE
When clicking on Generate Component Tests, nothing happens

### ISSUE THREAD

**Issue by dneeleman** [SimonTestNet/SimonTest#19]
When clicking on Generate Component Tests, nothing happens.
It has before, but ever since a couple of days it does not work anymore. I removed the plugin, reinstalled it. Removed Visual Code all together, but neither helped.

OS: MacOS Sierra 10.12.6 & Latest Visual Code.

**Comment by ManuelDeLeon** [comment]
I'll check it out.

**Comment by thekiba** [comment]
I have same problem.
Dev Console Output:
```
Activating extension `SimonTest.simontest` failed: Cannot find module 'slash'.
t.$localShowMessage @ mainThreadExtensionService.ts:117
```

**Comment by ManuelDeLeon** [comment]
You're right. Please pick up `v0.17.2`.

Thanks for the help!

**Comment by ManuelDeLeon** [comment]
At least the break was for a good cause. Fixed an issue so when you generate a component it adds the reference to the module =)

**Comment by dneeleman** [comment]
Can confirm it is working again! Thank you very much, this is very useful as a base for quick unit testing generating!
