### ISSUE TITLE
 Unexpected token / in JSON at position 128

### ISSUE THREAD

**Issue by nirolivier** [SimonTestNet/SimonTest#20]
Use case:
Right click on the component and generate component test
Result:
 Unexpected token / in JSON at position 128

**Comment by ManuelDeLeon** [comment]
Please include the component (remove anything not needed to reproduce the
error).

**Comment by nirolivier** [comment]
Hello,
Please, find the attachments below.
Environment: 
 - visual studio code v 1.18.0
 - Node 7.9.0
 - arch: ia32
Thanks,

[login.component.ts.zip](https://github.com/SimonTestNet/SimonTest/files/1479788/login.component.ts.zip)
[login.zip](https://github.com/SimonTestNet/SimonTest/files/1479806/login.zip)

**Comment by ManuelDeLeon** [comment]
I can't repro it =(

This seems related to #21 - My best guess is that it's an encoding or an invisible character. Try what I suggested there and let me know.

**Comment by ManuelDeLeon** [comment]
I think it's an issue with package.json or tslint.json (where the formatting rules are read). Can you attach both files?

**Comment by jgodi** [comment]
I am getting the same thing but on line 764. Would love to be able to use this extension! My package.json and tslint are all valid JSON.

**Comment by ManuelDeLeon** [comment]
Please attach the json files anyway, It's the only place I can think of
which can cause the error.

**Comment by kpaxton** [comment]
I had this issue as well. I noticed that I had put comments in the tslint.json file. Once I removed them it worked again.

**Comment by ManuelDeLeon** [comment]
This is fixed on v0.18.1
Thanks @kpaxton
