### ISSUE TITLE
How to set license key for VSCode extension

### ISSUE THREAD

**Issue by ntdog22** [SimonTestNet/SimonTest#27]
There is no documentation that I could find and no apparent VSCode settings (user, work-space, etc.) for inputting the license received after purchasing a subscription through GumRoad for SimonTest.

**Comment by ManuelDeLeon** [comment]
Looks like there was an issue with the reply I sent you this morning and it got lost along the way =(

-----------
Thank you for supporting SimonTest.

You will get a notification when your trial expires and it will let you enter the key. 

At that time you'll see the following box at the top of VSCode:
![image](https://user-images.githubusercontent.com/4257750/55516817-a4348a80-562b-11e9-9d26-92d7c9b2eba2.png)

And the following message on the lower right corner:
image.png
![image](https://user-images.githubusercontent.com/4257750/55516837-ae568900-562b-11e9-999e-4dd5c8bf5c75.png)

In the meantime there's nothing to worry about, the extension will work as normal. 

This is great feedback. I'll change the process and documentation so you can enter the key at any time, not just when it expires.

Thanks again,

Manuel

**Comment by ntdog22** [comment]
@ManuelDeLeon Any update on this issue? I have had SimonTest installed since the beginning of the year (2019) and I have never been prompted to input my license key (but have been paying for it this entire time!). Thank you!

**Comment by ManuelDeLeon** [comment]
Hi,

Please update SimonTest (at the moment v1.3.2). It includes a command to enter/update the license. To do so press Ctrl + Shift + P then type 'SimonTest: Update License'.

As always, please let me know if you encounter any issues.

Thanks again for the support.
