### ISSUE TITLE
Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by intellix** [SimonTestNet/SimonTest#3]
When trying to generate tests for a component that has a method and parameters I'm getting: `Cannot read property 'text' of undefined`

I'm not sure which version of TypeScript this plugin is using, but VSC is using 2.2.1

Example: 
```typescript
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'xc-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss'],
})
export class LoginComponent {

  constructor() { }

  redirect(something: string) { }
}
```

**Comment by SimonTestNet** [comment]
Ack! Sorry, for whatever reason I didn't get an email for this =(

Please update to v0.10.1
