### ISSUE TITLE
Hi I am working angular 7 project i am using the Simon test to generate the tests file. It is giving error as invalid charcater

### ISSUE THREAD

**Issue by bharathk9999** [SimonTestNet/SimonTest#35]
import { Component, OnInit, Input } from '@angular/core';
import { RootScope } from 'Scripts/src/app/services/rootscope.service';
import * as _ from 'lodash';
import { EnumModule } from 'Scripts/src/app/model/enum.module';
import { NgbActiveModal, NgbDateParserFormatter } from '@ng-bootstrap/ng-bootstrap';
import * as moment from 'moment';
import { ConfirmationDialogService } from 'Scripts/src/app/confirmation-dialog/confirmation-dialog.service';
import { ReportAutomationApiService } from 'Scripts/src/app/services/report-automation.serivce';
import { Broadcaster } from 'Scripts/src/app/factory/broadcaster.factory';
import { DatePipe } from '@angular/common';
import { NgbDateCustomParserFormatter } from 'Scripts/src/app/services/date-formatter.service';
import { NgbDateStruct, NgbTimeStruct, NgbDate } from '@ng-bootstrap/ng-bootstrap';

**Comment by ManuelDeLeon** [comment]
I can't repro the issue. Could you please copy/paste just enough of your component to reproduce the issue? Thanks.

**Comment by ewickenscs** [comment]
I am also having this issue, getting an error like so:
Invalid character. (9:1845) 7 | import { MyService } from "../_services/my.service"; 8 | import { MyComponent } from "./my.component"; > 9 | describe("MyComponent", () => {let component: MyComponent;let fixture: ComponentFixture<MyComponent>;beforeEach(() => {const myServiceStub = { getAllBatches: () => ....

**Comment by ManuelDeLeon** [comment]
I need a piece of code I can copy paste to VSCode.

**Comment by szalonna** [comment]
```ts
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class DemoService {
  static STATIC_ARRAY: string[] = [
    'hello',
    'from',
    'here'
  ]
}
```
and the error message
```
Invalid character. (3:345)
  1 | import { TestBed } from "@angular/core/testing";
  2 | import { DemoService } from "./demo.service";
> 3 | describe("DemoService", () => {let service: DemoService;beforeEach(() => {TestBed.configureTestingModule({providers: [ DemoService],});service = TestBed.get(DemoService);});it("can load instance", () => {expect(service).toBeTruthy();});it("STATIC_ARRAY defaults to: ['hello', 'from', 'here']", () => { expect(DemoService.STATIC_ARRAY).toEqual([\'hello\', \'from\', \'here\']);  });});
    |                                                                                                                                                                                                                                                                                                                                                         ^
```

**Comment by szalonna** [comment]
System info: 
```
Version: 1.44.2 (user setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by ManuelDeLeon** [comment]
Thank you for the repro. I see the problem and should have a fix soon.

**Comment by ManuelDeLeon** [comment]
Update to v1.8.7+ for the fix. Thanks again for the repro.
