### ISSUE TITLE
How to generate the **jasmine.createSpyObj** instead of  **Stubs** 

### ISSUE THREAD

**Issue by ravi-mone** [SimonTestNet/SimonTest#38]
Guys, This is not a code related question, but since it is related to unit testing and angular, posting here

I am using this extension
 https://marketplace.visualstudio.com/items?itemName=SimonTest.simontest

But when genearting the test cases 

[![enter image description here][1]][1]

It generates the **Stubs** for the services, Is there any way possible to make it generate the **jasmine.createSpyObj** 

Have gone through the site, https://simontest.net/ not have not found any info, can you guys please help me on how to generate the **jasmine.createSpyObj** instead of  **Stubs** 

  [1]: https://i.stack.imgur.com/tU95J.png

**Comment by ManuelDeLeon** [comment]
Hi there. Moving the spies up the chain prevents optimizations like caching and parallelization. It also promotes the anti-pattern of sharing state/spies between tests.

The best practice is to stub the dependencies and then spy on them in the tests. See [this example](https://gist.github.com/ManuelDeLeon/7a9f31cd62ca0cce3d41f5ed6ac93070#file-example-spec-ts).
