### ISSUE TITLE
TS Lint issues

### ISSUE THREAD

**Issue by jtc10005** [SimonTestNet/SimonTest#4]
When I generate component tests, there are some lint errors. Ex. using " instead of ', indention issues...
I realize that these are due to my lint rules and no issue with SimonTest.  
Is there any way to configure Simon test to either use my tslint config file or allow me to specify configuration options (like a simonTest.config.json file)?
For now I am adding 
`/* tslint:disable */`
at the top of the file to disable my lint rules. 
Thanks.

**Comment by SimonTestNet** [comment]
Working on it. I'll have it read tslint.json and use the appropriate quotation mark.

**Comment by intellix** [comment]
Quickfix for incorrectly generated indentations: Cmd Palette -> Format Document :)

**Comment by SimonTestNet** [comment]
v0.11.0 now uses the quotation mark specified in the tslint.json file.

@intellix Are the indentations wrong? Right now it uses VSCode's settings. Is there another tslint setting it should be picking up automatically?

**Comment by intellix** [comment]
I'm using 2 spaces indentation but was getting tabs on generated tests, which is defined in .editorconfig and tslint.json :)

**Comment by SimonTestNet** [comment]
@intellix Pick up v0.11.1. Thanks for the heads up.
