### ISSUE TITLE
My visual studio doesn’t print letter a

### ISSUE THREAD

**Issue by vishalkumarreddy** [SimonTestNet/SimonTest#41]
After uninstall and removed Simon test extension from my visual studio, the letter ‘a’ is not working.
For example if I am typing my code and press ‘a’ than warning symbol is shown as “command ‘extension.UpdateLicense’ not found” and also when I tried to install back Simontest and enter letter ‘a’ in search it again asks to enter the license for Simon test. I am not able to go forward with my work.

**Comment by SimonTestNet** [comment]
I'm sorry you're having issues but SimonTest doesn't have any key mappings, just an entry added to the right click menu for files, and the license is bound to VSCode's omni search menu (Ctrl + Shift + P). 

Please try any of the following:
- Close VSCode (kill process if need be) and restart it
- restarting your machine
- reinstalling the extension and remove it again
- reinstalling VSCode

**Comment by vishalkumarreddy** [comment]
Thanks for the reply
I had did all you said.
I had even reinstalled the Visual studio code.
You might replicate the issue by reinstalling the SimonTest extension
several times in VS code.
When I install it again even in fresh VS code, and enter letter ‘a’ than it
opens VS code’s Omni search menu and asks to enter the key.
I tried to buy the key but looks like you are using USA debit card and not
the India debit card.

Hope you will find a solution or it will be a deadlock and the programmer
cannot continue his work.

Currently using Atom developer tool because of necessity, but I am not used
to it yet.

Thanks,
Vishal.

**Comment by vishalkumarreddy** [comment]
Hi Simon Test,

Is there a dummy password or key where it just gives access to just
override the bug.
Hope you understand me.

Thank you,
Vishal.

**Comment by vishalkumarreddy** [comment]
Found the solution.
In the settings > keyboard shortcuts of Visual studio code > remove the
keyword element ‘a’ as shortcut and make it default.

Regards,
Vishal

**Comment by SimonTestNet** [comment]
Interesting. Thanks for the heads up in case someone else runs into it.
