### ISSUE TITLE
Inject and pull services from Injector within tests

### ISSUE THREAD

**Issue by intellix** [SimonTestNet/SimonTest#7]
Currently, mocks are created and referenced globally within a test. 

The recommended approach is to fetch them from the injector: https://angular.io/docs/ts/latest/guide/testing.html#!#service-from-injector

Currently:
```ts
describe('onSubmit', () => {
  it('should call activate if valid', () => {
    spyOn(userServiceStub, 'activate');
    component.onSubmit();
    expect(userServiceStub.activate).toHaveBeenCalled();
  });
});
```

Recommended: 
```ts
describe('onSubmit', () => {
  it('should call activate if valid', 
    inject([UserService], (userService: UserService) => {
      spyOn(userService, 'activate');
      component.onSubmit();
      expect(userService.activate).toHaveBeenCalled();
    });
});
```

When I log out the method being spied upon within my service, it's not a spy. But if I use the injector to fetch it first and then spy, it does work

**Comment by SimonTestNet** [comment]
Reading the docs it seems that [the recommended way](https://angular.io/docs/ts/latest/guide/testing.html#!#get-injected-service) is: 
`userService = fixture.debugElement.injector.get(UserService);`

I'll do more research.

**Comment by ManuelDeLeon** [comment]
I'll leave it as it is for now; until someone points out a problem with the current implementation or a benefit of using something different.

I acknowledge that using the recommended way wouldn't hurt, but in general I have a problem with doing/changing things "just because".

**Comment by intellix** [comment]
It's also how they look if you generate tests using Angular CLI :)

**Comment by ManuelDeLeon** [comment]
fyi, `v0.12.0` now uses injectors. See https://github.com/SimonTestNet/SimonTest/issues/10
