### ISSUE TITLE
Plugin breaks on latest Studio Code release

### ISSUE THREAD

**Issue by Alfred-W** [SimonTestNet/SimonTest#8]
I downloaded the latest version of Visual Studio Code (Version 1.11) and installed SimonTest (Version 0.11.1) but every time I run the plugin, I get this error:

> Unexpected token / in JSON at position 533

**Comment by ManuelDeLeon** [comment]
I have VSCode 1.11.1 and it works as expected. Please post the component you're using.

**Comment by Alfred-W** [comment]
I think there was something wrong with my component. I refactored some code, run the plugin and got the tests as expected.
Thanks!!!
